module.exports = [
  {
    user_id: 1,
    username: "ahalversen0",
    email: "mwaadenburg0@reverbnation.com",
    age: 86,
    gender: "other",
    country: "Bulgaria",
    job_title: "Account Coordinator",
    salary: 138374.9,
    join_date: "2/24/2020",
    active: false,
  },
  {
    user_id: 2,
    username: "ssawyer1",
    email: "frayman1@boston.com",
    age: 91,
    gender: "female",
    country: "Indonesia",
    job_title: "Research Assistant IV",
    salary: 144032.99,
    join_date: "7/20/2011",
    active: true,
  },
  {
    user_id: 3,
    username: "rsouza2",
    email: "wwitterick2@xinhuanet.com",
    age: 64,
    gender: "female",
    country: "Russia",
    job_title: "Analog Circuit Design manager",
    salary: 24666.58,
    join_date: "3/29/2019",
    active: false,
  },
  {
    user_id: 4,
    username: "lslowcock3",
    email: "nleeming3@upenn.edu",
    age: 77,
    gender: "other",
    country: "Pakistan",
    job_title: "Recruiter",
    salary: 47213.97,
    join_date: "6/22/2018",
    active: true,
  },
  {
    user_id: 5,
    username: "mrozec4",
    email: "ereynault4@cbc.ca",
    age: 60,
    gender: "male",
    country: "China",
    job_title: "Associate Professor",
    salary: 112055.53,
    join_date: "11/30/2018",
    active: false,
  },
  {
    user_id: 6,
    username: "atruran5",
    email: "swooland5@princeton.edu",
    age: 94,
    gender: "other",
    country: "Poland",
    job_title: "Product Engineer",
    salary: 71517.69,
    join_date: "3/24/2018",
    active: false,
  },
  {
    user_id: 7,
    username: "mseed6",
    email: "orudman6@edublogs.org",
    age: 38,
    gender: "female",
    country: "United States",
    job_title: "Payment Adjustment Coordinator",
    salary: 41408.28,
    join_date: "8/27/2011",
    active: false,
  },
  {
    user_id: 8,
    username: "dsawkin7",
    email: "wphlippsen7@census.gov",
    age: 79,
    gender: "female",
    country: "Cuba",
    job_title: "Nuclear Power Engineer",
    salary: 28551.95,
    join_date: "4/30/2016",
    active: false,
  },
  {
    user_id: 9,
    username: "sstradling8",
    email: "dbovis8@plala.or.jp",
    age: 93,
    gender: "male",
    country: "Kazakhstan",
    job_title: "General Manager",
    salary: 89246.34,
    join_date: "2/18/2011",
    active: true,
  },
  {
    user_id: 10,
    username: "ddenman9",
    email: "obenny9@blogtalkradio.com",
    age: 77,
    gender: "female",
    country: "France",
    job_title: "Safety Technician II",
    salary: 128790.49,
    join_date: "1/2/2012",
    active: true,
  },
];
